# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 13:38
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0002_auto_20170705_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(2010)]),
        ),
    ]
