# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-07 19:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0003_auto_20170705_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='slug',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
