# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-07 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0004_car_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='slug',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
